### ISSUE TITLE
bug: Codeblocks are not responsive

### ISSUE THREAD

**Issue by NEET64** [code100x/daily-code#368]
**The Problem**
The DIVs to display the code snippets and example code, are not responsive, in smaller screens the block remains the same size and the rest of the page shrinks, thus the code block overflows and breaks the page view. 

**To Reproduce**
1. You can notice the problem in mobile views, the page is responsive but the the code snippets overflow.

**Expected behavior**
The block should be horizontally scrollable and size should be respective to the parent container.

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/67575976/6316d26e-1d96-4265-b142-909e0ccbceaa)

**Info (please complete the following information):**
 - Browser: Chrome
 - Version: latest

**Comment by aryashubhanshu** [comment]
The issue has been fixed already, as in the latest pull it's not overflowing.

**Comment by hxdy-1** [comment]
@aryashubhanshu bro, I dont think so, the issue still persists: [see here](https://projects.100xdevs.com/tracks/6SbPPXGkG8QKFOTW9BmL/ts-4)

**Comment by aryashubhanshu** [comment]
I myself tried working on the issue, but when I pulled it was already resolved. The change is currently not showing on production, but eventually it will appear.

**Comment by hxdy-1** [comment]
@aryashubhanshu my bad sir, just tried it on my local machine, issue has been fixed!

**Comment by shantanuSakpal** [comment]
@hkirat @devsargam please close the issues which have been fixed, such as this one
